Modelagem inicial do monitor de preços
danka-tech/prices-monitor pull request #1
Opened 2022-08-14 01:22 UTC by mariasantosdev

## Descrição do problema
Inicio da modelagem do monitor de preços

## Solução proposta

Criamos três tabelas e tiramos algumas conclusões:
- Não faria sentido criar a entidade Provedor pois poderiamos ter essa info dentro do próprio produto. Com isso criamos uma outra tabela chamada Location pois um produto pode estar várias localizações. 
- Além disso haviamos acordado na discussão da modelagem adicionar os atributos nome e provedor, no entanto, conversando no momento do desenvolvimento não entendemos muito bem a diferença entre esses atributos e com isso não criamos o name(se houver alguma motivação favor comentar no PR).

2022-08-14 01:45 UTC, alexaugustobr requested changes

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/product/ProductType.java
> +    CLOUD, DATABASE;
Cloud parece que engloba tudo, o provedor é a nuvem.

O que vamos focar será principalmente em VPS, DB e servidor dedicado. Poderia ser VPS, DATABASE, DEDICATED_VPS

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/product/Product.java
> +    private String cpuCores;
Isso seria a quantidade de Cores, 10, 5, 8, etc.
Então é número.

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/product/Product.java
> +    private String provider;
Acredito que tem que ter uma classe provider (provedor/cloud).

Provider seria a Hetzner ou Linode.

Acredito que uma entidade separada com uma relação com Produto seja melhor.

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private List<Product> products = new ArrayList<>();
Um preço pertence a um produto. Não devemos misturar o preço a vários produtos.

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private CurrencyType currencyType;
Eu agruparia os valores de dolar, real e euro cada um em uma coluna, simplifica.

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +public class PriceHistory {
Como vamos saber qual é o preço atual?

2022-08-14 01:45 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/product/Product.java
> +public class Product {
Como vamos saber qual é o preço atual?

2022-08-14 01:50 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private CurrencyType currencyType;
To em dúvida nessa, não ficou ruim assim, mas penso que vai gerar mais complexidade nas Querys.
Não acredito que vamos adicionar mais que três tipos de valor, sempre BRL, USD e EUR.

2022-08-14 01:50 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private BigDecimal value;
Se tiver um produto grátis?

2022-08-14 01:51 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/product/Product.java
> +    private BigDecimal currentPrice;
Preço atual?? Mas é em EUR, Dolar ou Real?

Será que não é melhor criar uma classe Preço (que seria o histórico de preço) e relacionar com o produto?

2022-08-14 01:52 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/location/Location.java
> +public class Location {
Localização seria o país ou região certo?

2022-08-14 01:52 UTC, alexaugustobr commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private String location;
Por que não salvar um relacionamento com Location?

2022-08-16 00:19 UTC, Rayane420 commented on src/main/java/com/danka/tech/prices/monitor/location/Location.java
> +public class Location {
Isso, seria com relação aos países

2022-08-16 00:23 UTC, Rayane420 commented on src/main/java/com/danka/tech/prices/monitor/product/Product.java
> +    private String cpuCores;
Essa parte a gente acabou confundindo com a parte de Ram com GB junto, então vamos alterar

2022-08-20 22:25 UTC, mariasantosdev commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private BigDecimal value;
Não entendemos! esse é o l de long mas ficou parendo 01 kkkk, foi nesse sentido o comentário?

2022-08-20 22:25 UTC, mariasantosdev commented on src/main/java/com/danka/tech/prices/monitor/price/PriceHistory.java
> +    private BigDecimal value;
Tiramos o l para não ficar mais confuso kkk

2022-08-20 23:27 UTC, merged